# Generated by Django 4.2.4 on 2023-08-18 00:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('date_created', models.DateField(default=datetime.date(2023, 8, 18))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_credit', models.PositiveSmallIntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('S', 'Successful'), ('F', 'Failed')], max_length=2)),
                ('category', models.CharField(choices=[('g', 'groceries'), ('u', 'utilities')], max_length=2)),
                ('date', models.DateField(default=datetime.date(2023, 8, 18))),
                ('credits', models.ManyToManyField(to='credit_management.credit')),
            ],
        ),
    ]
